#!/bin/bash
local_ref="$1"
local_sha="$2"
remote_ref="$3"
if [ "$local_ref" = "refs/heads/develop" ] && [ "$remote_ref" = "refs/heads/master" ]; then
  echo "❌ Push develop→master запрещён. Используйте PR."
  exit 1
fi
exit 0
