// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteKey      string                 `protobuf:"bytes,1,opt,name=route_key,json=routeKey,proto3" json:"route_key,omitempty"` // config.RuleRouteKey(rule)
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                             // clientIP из getClientIP
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`                       // rule.RateLimit.RequestsPerSecond
	Burst         int64                  `protobuf:"varint,4,opt,name=burst,proto3" json:"burst,omitempty"`                      // rule.RateLimit.Burst
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *AllowRequest) GetRouteKey() string {
	if x != nil {
		return x.RouteKey
	}
	return ""
}

func (x *AllowRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllowRequest) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *AllowRequest) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type AllowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *AllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_ratelimit_proto protoreflect.FileDescriptor

const file_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x0fratelimit.proto\x12\x15features.ratelimit.v1\"e\n" +
	"\fAllowRequest\x12\x1b\n" +
	"\troute_key\x18\x01 \x01(\tR\brouteKey\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x14\n" +
	"\x05burst\x18\x04 \x01(\x03R\x05burst\")\n" +
	"\rAllowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2f\n" +
	"\x10RateLimitService\x12R\n" +
	"\x05Allow\x12#.features.ratelimit.v1.AllowRequest\x1a$.features.ratelimit.v1.AllowResponseBCZAgithub.com/basili4-1982/api-gateway/internal/features/ratelimitv1b\x06proto3"

var (
	file_ratelimit_proto_rawDescOnce sync.Once
	file_ratelimit_proto_rawDescData []byte
)

func file_ratelimit_proto_rawDescGZIP() []byte {
	file_ratelimit_proto_rawDescOnce.Do(func() {
		file_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelimit_proto_rawDesc), len(file_ratelimit_proto_rawDesc)))
	})
	return file_ratelimit_proto_rawDescData
}

var file_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ratelimit_proto_goTypes = []any{
	(*AllowRequest)(nil),  // 0: features.ratelimit.v1.AllowRequest
	(*AllowResponse)(nil), // 1: features.ratelimit.v1.AllowResponse
}
var file_ratelimit_proto_depIdxs = []int32{
	0, // 0: features.ratelimit.v1.RateLimitService.Allow:input_type -> features.ratelimit.v1.AllowRequest
	1, // 1: features.ratelimit.v1.RateLimitService.Allow:output_type -> features.ratelimit.v1.AllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ratelimit_proto_init() }
func file_ratelimit_proto_init() {
	if File_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelimit_proto_rawDesc), len(file_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ratelimit_proto_goTypes,
		DependencyIndexes: file_ratelimit_proto_depIdxs,
		MessageInfos:      file_ratelimit_proto_msgTypes,
	}.Build()
	File_ratelimit_proto = out.File
	file_ratelimit_proto_goTypes = nil
	file_ratelimit_proto_depIdxs = nil
}
