// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: authsvc.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // значение заголовка Authorization целиком
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`                // эффективный jwt.required (с учётом rule.Auth.Required)
	AnyRoles      []string               `protobuf:"bytes,3,rep,name=any_roles,json=anyRoles,proto3" json:"any_roles,omitempty"` // rule.Auth.Roles
	AllRoles      []string               `protobuf:"bytes,4,rep,name=all_roles,json=allRoles,proto3" json:"all_roles,omitempty"` // rule.Auth.RolesAll
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_authsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ValidateRequest) GetAnyRoles() []string {
	if x != nil {
		return x.AnyRoles
	}
	return nil
}

func (x *ValidateRequest) GetAllRoles() []string {
	if x != nil {
		return x.AllRoles
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                                                  // можно продолжать обработку (401 если false)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                                             // сообщение для 401
	HasClaims     bool                   `protobuf:"varint,3,opt,name=has_claims,json=hasClaims,proto3" json:"has_claims,omitempty"`                                                   // токен валиден и claims извлечены
	Claims        map[string]string      `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // результат ExtractClaims(claimMappings): claim → string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_authsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_authsvc_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateResponse) GetHasClaims() bool {
	if x != nil {
		return x.HasClaims
	}
	return false
}

func (x *ValidateResponse) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_authsvc_proto protoreflect.FileDescriptor

const file_authsvc_proto_rawDesc = "" +
	"\n" +
	"\rauthsvc.proto\x12\x10features.auth.v1\"}\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12\x1b\n" +
	"\tany_roles\x18\x03 \x03(\tR\banyRoles\x12\x1b\n" +
	"\tall_roles\x18\x04 \x03(\tR\ballRoles\"\xda\x01\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"has_claims\x18\x03 \x01(\bR\thasClaims\x12F\n" +
	"\x06claims\x18\x04 \x03(\v2..features.auth.v1.ValidateResponse.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012`\n" +
	"\vAuthService\x12Q\n" +
	"\bValidate\x12!.features.auth.v1.ValidateRequest\x1a\".features.auth.v1.ValidateResponseB>Z<github.com/basili4-1982/api-gateway/internal/features/authv1b\x06proto3"

var (
	file_authsvc_proto_rawDescOnce sync.Once
	file_authsvc_proto_rawDescData []byte
)

func file_authsvc_proto_rawDescGZIP() []byte {
	file_authsvc_proto_rawDescOnce.Do(func() {
		file_authsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authsvc_proto_rawDesc), len(file_authsvc_proto_rawDesc)))
	})
	return file_authsvc_proto_rawDescData
}

var file_authsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authsvc_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: features.auth.v1.ValidateRequest
	(*ValidateResponse)(nil), // 1: features.auth.v1.ValidateResponse
	nil,                      // 2: features.auth.v1.ValidateResponse.ClaimsEntry
}
var file_authsvc_proto_depIdxs = []int32{
	2, // 0: features.auth.v1.ValidateResponse.claims:type_name -> features.auth.v1.ValidateResponse.ClaimsEntry
	0, // 1: features.auth.v1.AuthService.Validate:input_type -> features.auth.v1.ValidateRequest
	1, // 2: features.auth.v1.AuthService.Validate:output_type -> features.auth.v1.ValidateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authsvc_proto_init() }
func file_authsvc_proto_init() {
	if File_authsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authsvc_proto_rawDesc), len(file_authsvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authsvc_proto_goTypes,
		DependencyIndexes: file_authsvc_proto_depIdxs,
		MessageInfos:      file_authsvc_proto_msgTypes,
	}.Build()
	File_authsvc_proto = out.File
	file_authsvc_proto_goTypes = nil
	file_authsvc_proto_depIdxs = nil
}
